name: Python application

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Send Results to Telegram
      run: python main.py
    - name: Test with pytest
      run: |
        pytest
    - name: |
      run: python test_main.py
      env:
        TOKEN_TELEGRAM_BOT: ${{ secrets.TOKEN_TELEGRAM_BOTN }}
        id_chat: ${{ secrets.id_chat }}




